### ISSUE TITLE
Introspect endpoint does not expose `account_id`

### ISSUE THREAD

**Issue by tylernix** [Finch-API/finch-api-node#219]
The [Introspect](https://developer.tryfinch.com/docs/reference/9d248a993cb53-introspect) endpoint returns `account_id` but it is not exposed by the SDK.

**Comment by hdemirev** [comment]
`account_id` was added to the SDK with [5.10.0](https://github.com/Finch-API/finch-api-node/pull/226/files#diff-8d83eb14f6c95be1cc373797ac54633d02ba19e9788bf86cf2f3c16d245f7969R36)
