### ISSUE TITLE
Can't get access token

### ISSUE THREAD

**Issue by djkirby** [Finch-API/finch-api-node#283]
See https://github.com/Finch-API/finch-api-node/commit/22e66e08d5d848deabf190e2334e00eb4645d723#r137374844

getAccessToken is passing a `Authorization: null` header, but this is only checking for lowercase "authorization". So it throws the `Could not resolve authentication method. Expected either accessToken, sandboxClientId or sandboxClientSecret to be set. Or for one of the "Authorization" or "Authorization" headers to be explicitly omitted` Error.

```tsx
const finch = new Finch({
  clientId: "...",
  clientSecret: "...",
});
const accessToken = await finch.getAccessToken(<code>, {
  redirectUri: "...",
});

```

**Comment by hdemirev** [comment]
@djkirby a [change was just released](https://github.com/Finch-API/finch-api-node/pull/291) to `accessTokens.create` that makes the `client_id` and `client_secret` optional (they'll be read from the client), which should make that flow more streamlined. Please flag if you run into any issues there, the plan is to deprecate `getAccessToken` and move to `accessTokens.create`
