### ISSUE TITLE
Creating access token requires redirect_uri

### ISSUE THREAD

**Issue by johnMorone** [Finch-API/finch-api-node#304]
`accessTokens.create` requires a `redirect_uri` on the `body` param. Otherwise, the following Typescript error is thrown:

```
TS2345: Argument of type { code: string; } is not assignable to parameter of type AccessTokenCreateParams
Property redirect_uri is missing in type { code: string; } but required in type AccessTokenCreateParams
access-tokens.d.ts(15, 5): redirect_uri is declared here.
```

However, when setting up Finch Connect with the [React SDK](https://github.com/Finch-API/react-connect), rather than a Redirect Flow, then there is no corresponding `redirect_uri`. Passing any `redirect_uri` will cause the api call to fail with the following error:

```
"400 Invalid grant: authorization code is invalid. Are you sure that you typed it correctly or have not already exchanged it for a token?"
```

`ts-ignore` is a valid workaround, but there should be some official way to use this library along with the React SDK under Typescript without such a workaround. I believe making this parameter optional (along with a comment explaining it is needed when using the Redirect flow, but not with the React SDK) would be an appropriate solution.

**Comment by dackerman** [comment]
Thank you for the report! Indeed that's not a great experience, we'll look into this.
