### ISSUE TITLE
Property 'commuter' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'

### ISSUE THREAD

**Issue by kajan746** [Finch-API/finch-api-node#373]
Hi there!

I am getting these errors when i install finch. Why this is happening?

```
node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:94:5 - error TS2411: Property 'commuter' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

94     commuter?: BenefitFeaturesAndOperations | null;
       ~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:95:5 - error TS2411: Property 'custom_post_tax' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

95     custom_post_tax?: BenefitFeaturesAndOperations | null;
       ~~~~~~~~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:96:5 - error TS2411: Property 'custom_pre_tax' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

96     custom_pre_tax?: BenefitFeaturesAndOperations | null;
       ~~~~~~~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:97:5 - error TS2411: Property 'fsa_dependent_care' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

97     fsa_dependent_care?: BenefitFeaturesAndOperations | null;
       ~~~~~~~~~~~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:98:5 - error TS2411: Property 'fsa_medical' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

98     fsa_medical?: BenefitFeaturesAndOperations | null;
       ~~~~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:99:5 - error TS2411: Property 'hsa_post' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

99     hsa_post?: BenefitFeaturesAndOperations | null;
       ~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:100:5 - error TS2411: Property 'hsa_pre' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

100     hsa_pre?: BenefitFeaturesAndOperations | null;
        ~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:101:5 - error TS2411: Property 's125_dental' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

101     s125_dental?: BenefitFeaturesAndOperations | null;
        ~~~~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:102:5 - error TS2411: Property 's125_medical' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

102     s125_medical?: BenefitFeaturesAndOperations | null;
        ~~~~~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:103:5 - error TS2411: Property 's125_vision' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

103     s125_vision?: BenefitFeaturesAndOperations | null;
        ~~~~~~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:104:5 - error TS2411: Property 'simple' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

104     simple?: BenefitFeaturesAndOperations | null;
        ~~~~~~

node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:105:5 - error TS2411: Property 'simple_ira' of type 'BenefitFeaturesAndOperations | null | undefined' is not assignable to 'string' index type 'BenefitFeaturesAndOperations | null'.

105     simple_ira?: BenefitFeaturesAndOperations | null;
        ~~~~~~~~~~


Found 12 errors in the same file, starting at: node_modules/@tryfinch/finch-api/resources/hris/benefits/benefits.d.ts:94

error Command failed with exit code 2.
```

**Comment by RobertCraigie** [comment]
Hey @kajan746, where exactly are these errors happening? When you run `tsc`?

I suspect you might have an import that looks like this
```
import { thing } from '@tryfinch/finch-api/src';
```
i.e. any import that includes `src`. These files are only included for better IDE experience and shouldn't be actually used at runtime.

**Comment by kajan746** [comment]
Hi @RobertCraigie! Sorry for the late reply.

![image](https://github.com/Finch-API/finch-api-node/assets/4878773/dcf6be62-a9fe-4262-b511-6e2e1e61078d)

I am getting the above error when i commit my changes. And following is my tsconfig content
`{
  "compilerOptions": {
    "target": "ES2020", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs", /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "outDir": "dist", /* Redirect output structure to the directory. */
    "rootDir": "src", /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    "strict": true, /* Enable all strict type-checking options. */
    "alwaysStrict": true, /* Parse in strict mode and emit "use strict" for each source file. */
    "moduleResolution": "node", /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "esModuleInterop": true, /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "experimentalDecorators": true,
    "baseUrl": "src"
  },
  "exclude": [
    "node_modules",
  ],
  "include": [
    "src/**/*",
    "src/test/**/*",
    "tests/**/*",
  ]
}`


And No, I just imported like this.
`import Finch from '@tryfinch/finch-api';`

**Comment by RobertCraigie** [comment]
Thanks @kajan746, if you manually modify the `BenefitsSupport` type in the `benefits.d.ts` file to use this index signature instead, does the type error go away?

```
[k: string]: BenefitFeaturesAndOperations | null | undefined;
```

**Comment by kajan746** [comment]
Yes, but we cannot do that right since its in the node modules?

**Comment by RobertCraigie** [comment]
yes sorry @kajan746 we are working on fixing this on our end & I wanted to verify if the solution we were planning on using would work for your case.

**Comment by kajan746** [comment]
Oh okay.. it worked after replacing like this
`export interface BenefitsSupport {
    commuter?: BenefitFeaturesAndOperations | null | undefined;
    custom_post_tax?: BenefitFeaturesAndOperations | null | undefined;
    custom_pre_tax?: BenefitFeaturesAndOperations | null | undefined;
    fsa_dependent_care?: BenefitFeaturesAndOperations | null | undefined;
    fsa_medical?: BenefitFeaturesAndOperations | null | undefined;
    hsa_post?: BenefitFeaturesAndOperations | null | undefined;
    hsa_pre?: BenefitFeaturesAndOperations | null | undefined;
    s125_dental?: BenefitFeaturesAndOperations | null | undefined;
    s125_medical?: BenefitFeaturesAndOperations | null | undefined;
    s125_vision?: BenefitFeaturesAndOperations | null | undefined;
    simple?: BenefitFeaturesAndOperations | null | undefined;
    simple_ira?: BenefitFeaturesAndOperations | null | undefined;
    [k: string]: BenefitFeaturesAndOperations | null | undefined;
}`

**Comment by RobertCraigie** [comment]
This should be fixed in `v5.22.9`, please try it out and confirm :)

**Comment by kajan746** [comment]
Latest NPM package is not available yet. i'll let you know once its ready

**Comment by yjp20** [comment]
Hey @kajan746, the new version of the finch sdk has been released!

**Comment by kajan746** [comment]
Great! thank you :)

**Comment by kajan746** [comment]
And it works!
