### ISSUE TITLE
Getting new error -  Can't resolve 'crypto' on code compile 

### ISSUE THREAD

**Issue by manojgsequoia** [Finch-API/finch-api-node#494]
Team, after installing `"@tryfinch/finch-api": "^6.10.0"` during code compile we are getting below error. 

We are using RSpack as our bundler.

Node: v20.9.0
yarn: 1.22.19
npm: 10.1.0

ERROR in ./node_modules/@tryfinch/finch-api/resources/webhooks.mjs
  × Resolve error: Can't resolve 'crypto' in 'code/node_modules/@tryfinch/finch-api/resources'
   ╭─[1:1]
 1 │ // File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.
 2 │ import { APIResource } from "../resource.mjs";
 3 │ import { createHmac } from 'crypto';
   ·                            ────────
 4 │ import { getRequiredHeader } from "../core.mjs";
 5 │ export class Webhooks extends APIResource {
   ╰────

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
Rspack compiled with 2 errors in 2.25 s

<img width="748" alt="image" src="https://github.com/user-attachments/assets/4252e716-8f89-4b72-9eb8-65ca141f3550">

**Comment by manojgsequoia** [comment]
@RobertCraigie @rattrayalex @aneeshvaidya  @diaswrd Please help us in fixing it

**Comment by jordanbrauer** [comment]
hey @manojgsequoia , can you try the latest version [v6.10.2](https://github.com/Finch-API/finch-api-node/releases/tag/v6.10.2), and see if the issue is fixed for you?
