### ISSUE TITLE
Getting CORS error while calling session API from Frontned

### ISSUE THREAD

**Issue by manojgsequoia** [Finch-API/finch-api-node#498]
Hi Team, i'm trying to generate session id by following below implementation in `front end (via browser)` of my application. But getting CORS error as shown in below screenshot. I'm passing our own unique entities while calling it. The same curl works in Postman and in our backend application. Is there anyway we can call it in frontend without getting cors error?

 Can someone please help?

<img width="697" alt="image" src="https://github.com/user-attachments/assets/f7ffcc0b-0eb2-4bae-84d7-b99989b8e62d">

<img width="770" alt="image" src="https://github.com/user-attachments/assets/8dcb03a4-23a5-48c8-ad3e-fd0b20187cf7">

**Comment by manojgsequoia** [comment]
@rattrayalex  @diaswrd  @alexromano pls help here.

**Comment by jordanbrauer** [comment]
@manojgsequoia I'll take a look today!

**Comment by M-Shehu** [comment]
Hi @manojgsequoia. The connect session endpoints cannot be called on your frontend because it requires a client secret that can't be exposed to a frontend client. You would need to proxy the request through your backend service
